language: ruby
services:
  - postgresql
rvm:
  - 2.3.1
before_install:
  - gem update --system
  - gem --version
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database simplehr_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate spec

notifications:
  email:
    - aboobackervyd+karmahrm@gmail.com
    - mastersdream+karmahrm@gmail.com
    - sobisunny+karmahrm@gmail.com
